config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'pages#dashboard'
  get 'dashboard', to: 'pages#dashboard'

  # routes will start with /offices/<office.slug>/
  resources :offices, param: :slug do
    shallow_actions = %i[edit update show]

    member do
      get :destroy_modal
    end

    resources :members, only: %i[index new create] do
      member do
        patch :change_role
      end
    end

    resources :search_users, only: [:index], defaults: { format: :json }

    resources :templates, only: shallow_actions.push(:destroy) do
      member do
        get :destroy_modal
      end
    end

    resources :model_properties, only: shallow_actions.push(:destroy) do
      member do
        get :destroy_modal
      end
    end

    resources :documents, only: [:destroy] do
      member do
        get :destroy_modal
      end
    end

    resources :instances, only: shallow_actions.push(:destroy) do
      resources :documents

      member do
        get :destroy_modal
      end
    end

    resources :instance_properties, only: shallow_actions
    resources :data_models do
      member do
        get :destroy_modal
      end
      resources :model_properties, except: shallow_actions
      resources :instances, except: shallow_actions
      resources :templates, except: shallow_actions
    end
  end
end

app/models/instance.rb
class Instance < ApplicationRecord
  has_many :properties, class_name: 'InstanceProperty', dependent: :destroy, autosave: true
  has_many :documents, dependent: :destroy
  belongs_to :data_model
  belongs_to :created_by, class_name: 'User'

  def hashed_properties
    properties.each_with_object({}) do |prop, hash|
      hash[prop.code] = prop.value
    end
  end
end

app/controllers/instances_controller.rb
class InstancesController < ApplicationController
  layout 'office'

  def index
    @instances = if params[:search].present?
                   search_instances
                 else
                   data_model.instances.page(params[:page])
                 end
    @data_models = current_office.data_models.where.not(id: @data_model.id)
    @properties = @data_model.properties.where(header_visibility: true)
    @params = request.query_parameters
  end

  def new
    # props = data_model.properties.collect { |prop| { name: prop.code } }
    @instance = data_model.instances.new data_model_name: data_model.name
    CreateInstanceService.build_instance_properties_from_data_model @instance
    # @instance.properties.build
  end

  def create
    result = Instances::CreateService.execute(properties_params, data_model, current_user)
    @instance = result.payload[:instance]

    if result.success?
      redirect_to [current_office, @instance],
                  notice: "#{data_model.name} was successfully created"
    else
      @validated = true
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @instance = fetch_instance
    @data_model = @instance.data_model
    @properties = @instance.properties.joins(:model_property).order('model_properties.position DESC')
    @documents = @instance.documents.order('documents.created_at DESC')
  end

  def edit
    @instance = current_office.instances.find(params[:id])
    @data_model = @instance.data_model
  end

  def destroy_modal
    @instance = fetch_instance
    @data_model = @instance.data_model
  end

  def destroy
    @instance = fetch_instance
    data_model = @instance.data_model

    @instance.destroy

    redirect_to [current_office, data_model, :instances], notice: 'Entry deleted'
  end

  private

  def fetch_instance
    current_office.instances.find(params[:id])
  end

  def data_model
    @data_model ||= current_office.data_models.find(params[:data_model_id])
  end

  def properties_params
    params.require(:properties).permit(data_model.properties.pluck(:code))
  end

  def search_instances
    @matched_properties = data_model.instance_properties.where('lower(instance_properties.value) LIKE ?',
                                                               "%#{params[:search].downcase}%")
    data_model.instances.where(id: @matched_properties.select('instance_id').distinct).page(params[:page])
  end
end

app/views/instances/_destroy_modal.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-header">
      <h5 class="modal-title">Delete <b><%= data_model.name %></b> entry</h5>
    </div>
    <div class="modal-body">

      This <b>entry</b> contains
      <span class='text-warning'>
        <%= pluralize(instance.documents.count, 'Document') %>
      </span>
    </div>
    <div class="modal-footer">
      <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
      <%= link_to 'Delete', [office, instance], method: :delete, class: 'btn btn-danger' %>
    </div>
  </div>
</div>

app/views/instances/_documents.html.erb
<% disabled_class = ''%>
<% if @data_model.templates.count.zero? %>
  <% disabled_class = 'disabled' %>
  <div class="col-12">
    <div class='alert alert-warning' %>
      This Data model does not have any document templates.
      <% if current_membership.admin? %>
        <%= link_to 'Add document template', [:new, current_office, instance.data_model, :template], remote: true %>
      <% end %>
    </div>
  </div>
<% end %>
<div class="d-flex justify-content-between mb-2 mt-0">
  <h5 class='mb-0 pt-1'>Documents</h5>
  <div>
    <%= link_to [:new, current_office, instance, :document],
      class: "btn btn-info btn-sm #{disabled_class}",
      remote: true do %>
      <i class="fa fa-circle-plus me-1"></i> Generate
    <% end %>
  </div>

</div>


<div class='row px-2'>
  <% documents.each do |document| %>
    <div class="mb-2 px-1 col-md-6">
      <div class='card'>
        <div class="card-body">
          <div class='d-flex justify-content-start'>
            <div>
              <% if document.file.signed_id %>
                <% if document.file.representable? %>
                    <div class='border float-start' width=100%>
                      <%= image_tag document.file.representation(resize_to_limit: [128, 128]) %>
                    </div>
                <% end %>
              <% end %>
            </div>
            <div class='ms-3'>
              <h5 class='mb-0 text-truncate'> <%= document.name.first(20)  %></h5>
              <small class='text-secondary'><%= document.template&.name || 'Deleted'  %> Template</small>
              <div class='text-dark mt-2'>
                <%= document.created_at.strftime('%B %d %Y %r') %>
              </div>
              <div class='mt-2'>
                <% if document.file.present? %>
                  <%= link_to rails_blob_path(document.file, disposition: "attachment"), class: 'no-decoration' do %>
                    <i class="fa fa-download text-success me-1"></i>
                  <% end %>
                <% end %>

                <%= link_to [:destroy_modal, current_office, document], remote: true do %>
                  <i class="fa fa-trash text-danger"></i>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
  <% if documents.count.zero? %>
    <div class="card">
      <div class="card-body">
        <div class="row">
          <small class='text-center text-dark'>
            No documents found
          </small>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/instances/_form.html.erb
<div class='card'>
  <div class='card-body'>
    <%= form_for instance, url: url do |f| %>
      <div class='row'>
        <%= fields_for :properties do |fprop| %>
          <%= fprop.hidden_field :test %>
          <% instance.properties.each do |prop| %>
            <div class="col-md-6">
              <div class="mb-3">
                <%= fprop.label prop.code, class: 'form-label' do %>
                  <%= prop.name %>
                  <span class='badge bg-light rounded-pill'><%= prop.code %></span>
                <% end %>
                <% if validated %>
                  <% prop_class = prop.valid? ? 'is-valid' : 'is-invalid' %>
                  <%= fprop.text_field prop.code, class: "form-control #{prop_class}", aria: { describedby: "validation-#{prop.code}" } %>
                  <div id="validation-<%= prop.code %>" class="invalid-feedback">
                    <% prop.errors.each do |error| %>
                      <%= error.full_message %>
                    <% end %>
                  </div>
                <% else %>
                  <%= fprop.text_field prop.code, class: "form-control" %>
                <% end %>
              </div>
            </div>
          <% end %>
        <% end %>

        <div class="col-12">
        <% if instance.data_model.properties.count.zero? %>
          <div class='offset-md-3 col-md-6'>
           <%= f.submit 'Create Empty Instance', class: 'btn btn-lg btn-success form-control' %>
          </div>
        <% else %>
            <div class="mb-2">
              <%= f.submit class: 'btn btn-success float-end' %>
            </div>
        <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/instances/destroy_modal.js.erb
<% options = {
  instance: @instance,
  data_model: @data_model,
  office: current_office
}%>

modal_div = document.getElementById('app-modal')

modal_div.innerHTML = "<%= j render 'destroy_modal', options %>"

var app_modal = new bootstrap.Modal(document.getElementById('app-modal'))

app_modal.show()

app/views/instances/edit.html.erb
<% breadcrumb :edit_instance, @instance %>

<h5>Editing <%= @instance.data_model.name %></h5>

<%= render 'form', instance: @instance, data_model: @data_model,  url: [current_office, @instance] %>

app/views/instances/index.html.erb
<% breadcrumb :instances, @data_model %>

<div class="col-12 mb-2">
  <% if @data_models.count.zero? %>
    <h5> <%= @data_model.name %></h5>
  <% else %>
    <div class="dropdown">
      <button class="btn btn-outline-primary dropdown-toggle" type="button" id="dataModelDropdown" data-bs-toggle="dropdown" aria-expanded="false">
        <%= @data_model.name %>
      </button>
      <ul class="dropdown-menu" aria-labelledby="dataModelDropdown">
        <% @data_models.each do |data_model| %>
          <li>
            <%= link_to data_model.name, [current_office, data_model, :instances], class: 'dropdown-item' %>
          </li>
        <% end %>
      </ul>
    </div>
  <% end %>
</div>
<div class="col-12">
  <div class="card">
    <div class="card-body">
      <div class="d-flex justify-content-between">
        <div class>
          <%= link_to new_office_data_model_instance_path(@data_model.id, office_slug: current_office.slug), class: 'btn btn-info btn-sm' do %>
            <i class="fa fa-circle-plus me-1"></i> Add
          <% end %>
        </div>
        <div>
          <% search_params = @params.merge({
              office_slug: current_office.slug,
              data_model_id: @data_model.id,
             })
          %>
          <%= form_tag office_data_model_instances_path(search_params), method: :get, class: 'float-end' do %>
            <div class='input-group'>
              <%= search_field_tag :search, params[:search], class: 'form-control', placeholder: 'Search', aria: { label: 'Search instance' } %>
              <%= submit_tag 'Search', class: 'btn btn-sm btn-primary' %>
            </div>
          <% end %>
        </div>
      </div>
      <div class='table-responsive'>
        <table class='table table-hover table-striped table-compact table-borderless'>
          <thead>
            <tr>
              <th> ID </th>
              <% @properties.each do |property| %>
                <th style='white-space: nowrap;'><%= property.name %></th>
              <% end %>
              <th class='text-center' s>Docs<th>
              <th></th>
            </tr>
          </thead>

          <tbody>
            <% @instances.each do |instance| %>
              <tr>
                <% props = instance.hashed_properties %>
                <td>
                  <%= link_to "##{instance.data_model.name}-#{instance.id}", [current_office, instance] %>
                </td>
                <% @properties.each do |property| %>
                  <td><%= props[property.code] %></td>
                <% end %>
                <td class='text-center'><%= instance.documents.count %></td>
                <td class='text-end pe-3'>
                  <%= link_to [current_office, instance], class: 'z-1 no-decoration me-2' do%>
                    <i class="fa fa-expand text-secondary"></i>
                  <% end %>

                  <%= link_to [:destroy_modal, current_office, instance], remote: true, class: 'z-1' do%>
                    <i class="fa fa-trash text-danger"></i>
                  <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
      <%= paginate @instances %>
    </div>
  </div>
</div>

app/views/instances/new.html.erb
<% breadcrumb :new_instance, @data_model %>

<% if @data_model.properties.count.zero? %>
  <div class="alert alert-warning" role="alert">
    This Data Model does not have any defined properties.
    <% if current_membership.admin? %>
      <%= link_to [:new, current_office, @data_model, :model_property], remote: true do %>
        Add properties here
      <% end %>
    <% end %>
  </div>
<% end %>
<h5>New <%= @data_model.name %> </h5>

<div id='new-instance-form'>
  <%= render 'form', instance: @instance, data_model: @data_model, url: [@data_model.office, @data_model, :instances], validated: @validated %>
</div>

app/views/instances/show.html.erb
<% breadcrumb :instance, @instance, current_office %>
<div class="row">
  <div class="col-sm-3 mb-2">
    <h5 class='pt-1 mb-2'> <%= @data_model.name %></h1>
    <div class="card">
      <div class="card-body">
        <% @properties.each do |property| %>
          <div id='property-<%= property.id %>'>
            <%= render 'instance_properties/instance_property', property: property, office: current_office %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  <div class="col-sm-9">
    <%= render 'documents', documents: @documents, office: current_office, instance: @instance %>
  </div>
</div>