config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'pages#dashboard'
  get 'dashboard', to: 'pages#dashboard'

  # routes will start with /offices/<office.slug>/
  resources :offices, param: :slug do
    shallow_actions = %i[edit update show]

    member do
      get :destroy_modal
    end

    resources :members, only: %i[index new create] do
      member do
        patch :change_role
      end
    end

    resources :search_users, only: [:index], defaults: { format: :json }

    resources :templates, only: shallow_actions.push(:destroy) do
      member do
        get :destroy_modal
      end
    end

    resources :model_properties, only: shallow_actions.push(:destroy) do
      member do
        get :destroy_modal
      end
    end

    resources :documents, only: [:destroy] do
      member do
        get :destroy_modal
      end
    end

    resources :instances, only: shallow_actions.push(:destroy) do
      resources :documents

      member do
        get :destroy_modal
      end
    end

    resources :instance_properties, only: shallow_actions
    resources :data_models do
      member do
        get :destroy_modal
      end
      resources :model_properties, except: shallow_actions
      resources :instances, except: shallow_actions
      resources :templates, except: shallow_actions
    end
  end
end

app/models/office.rb
class Office < ApplicationRecord
  has_many :data_models, dependent: :destroy
  has_many :templates, through: :data_models
  has_many :instances, through: :data_models
  has_many :model_properties, through: :data_models, source: :properties
  has_many :instance_properties, through: :instances, source: :properties
  has_many :members, dependent: :destroy
  has_many :users, through: :members
  has_many :documents, through: :instances
  belongs_to :created_by, class_name: 'User'

  validates :slug, format: { with: /\A[a-zA-Z0-9-]+\Z/ }, uniqueness: true

  def to_param
    slug
  end
end

app/controllers/offices_controller.rb
class OfficesController < ApplicationController
  layout 'office'

  def index
    @memberships = current_user.members.includes(:office).order("offices.#{sort_column} #{sort_direction}")

    if params[:search]
      @memberships = @memberships.where('lower(offices.name) LIKE ?', "%#{params[:search].downcase}%")
    end
  end

  def new
    @office = current_user.offices.new
  end

  def create
    @office = current_user.offices.new office_params.merge(created_by: current_user)
    @office.members.build(user: current_user, member_role: :admin)

    if @office.save
      redirect_to [@office, :data_models], notice: 'Office was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    if current_office.data_models.count.positive?
      redirect_to [current_office, office.data_models.first, :instances]
    else
      redirect_to [:new, current_office, :data_model]
    end
  end
  # def show
  #   @current_office = office
  #   @instances = current_office.instances.order('instances.created_at DESC').page(params[:page])

  #   @data_models = current_office.data_models.page(params[:page])
  #   if @data_models.count.zero?
  #     render :empty
  #   end
  #   @params = request.query_parameters
  # end

  def edit
    @current_office = office
    authorize_admin!
    office
  end

  def update
    @current_office = office
    authorize_admin!

    if current_office.update(office_params)
      redirect_to [:edit, current_office], notice: 'Office was successfully updated.'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy_modal
    current_office
  end

  def destroy
    current_office.destroy
    redirect_to [:offices], notice: 'Office deleted'
  end

  private

  def office_params
    params.require(:office).permit(:name, :slug, :thumbnail_color)
  end

  def office
    @office ||= current_user.created_offices.find_by(slug: params[:slug])
  end

  def sort_column
    return params[:sort] if %w[name slug].include? params[:sort]

    'name'
  end

  def sort_direction
    params[:direction] == 'desc' ? 'DESC' : 'ASC'
  end
end

app/helpers/office_helper.rb
module OfficeHelper
  SORT_ITEMS = [
    { type: :label, name: 'Sort' },
    { type: :option, name: 'Name', code: 'name' },
    { type: :option, name: 'Slug', code: 'slug' }
  ].freeze

  def find_sort_item_by_code(code)
    code ||= 'name'
    SORT_ITEMS.find do |item|
      item[:code] == code
    end
  end

  def office_sort_options
    SORT_ITEMS
  end
end

app/views/offices/_destroy_modal.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-header">
      <h5 class="modal-title">Delete <%= office.name %></h5>
    </div>
    <div class="modal-body">
        This <b>Office</b> contains:

        <ul>
          <li>
            <span class='text-warning'>
              <%= pluralize(office.instances.count, 'entry') %>
            </span>
          </li>
          <li>
            <span class='text-warning'>
              <%= pluralize(office.documents.count, 'document') %>
            </span>
          </li>
          <li>
            <span class='text-warning'>
              <%= pluralize(office.data_models.count, 'template') %>
            </span>
          </li>
          <li>
            <span class='text-warning'>
              <%= pluralize(office.members.count, 'member') %>
            </span>
          </li>
        </ul>
      </p>
    </div>
    <div class="modal-footer">
      <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
      <%= link_to 'Delete', [office], method: :delete, class: 'btn btn-danger' %>
    </div>
  </div>
</div>

app/views/offices/_empty.html.erb
<div class="card">
  <div class="card-body">
    <div class="text-center">
      Nothing to show
    </div>
  </div>
</div>

app/views/offices/_form.html.erb
<%= form_with(model: office, url: url) do |f| %>
  <% if office.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(office.errors.count, "error") %> prohibited this form from being saved:</h2>

      <ul>
        <% office.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name, 'Office name', class: 'form-field' %>
    <%= f.text_field :name, class: 'form-control', 'data-slug-target': 'name', 'data-action': 'keyup->slug#updateSlug' %>
  </div>

  <div class="form-group mb-3">
    <%= f.label :slug, 'Office slug', class: 'form-field' %>
    <%= f.text_field :slug, class: 'form-control', 'data-slug-target': 'slug' %>
  </div>

  <div class="form-group mb-3 visually-hidden" data-controller='offices'>
    <%= f.label :thumbnail_color, 'Thumbnail Color (#hex-value)', class: 'form-field' %>
    <%= f.text_field :thumbnail_color, class: 'form-control', 'data-offices-target': 'thumbnailColor' %>
  </div>

  <div class="actions">
    <%= f.submit 'Save', class: 'btn btn-success' %>
  </div>
<% end %>

app/views/offices/_models.html.erb
<div class="card mt-2">
  <div class="card-body">
    <div class="row mb-2">
      <div class="col-sm-5">
        <%= link_to new_office_data_model_path(office.slug), class: 'btn btn-info  btn-sm' do %>
          <i class="fa fa-circle-plus me-1"></i> New Data Model
        <% end %>
      </div>
    </div>
    <table class='table table-striped table-borderless table-hover'>
      <thead>
        <tr>
          <th>Name</th>
          <th>Properties</th>
          <th class='tb-actions'>Actions</th>
        </tr>
      </thead>
      <tbody>
        <% office.data_models.each do |data_model| %>
          <tr>
            <td>
              <%= link_to data_model.name, office_data_model_path(data_model.id, office_slug: office.slug) %>
            </td>
            <td class='text-dark'>
              <%= data_model.properties.pluck(:name).join(', ') %>
            </td>
            <td class='tb-actions'>
              <%= link_to edit_office_data_model_path(data_model, office_slug: office.slug), class: 'text-muted' do %>
                <i class="fa fa-pen-to-square"></i>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/offices/destroy_modal.js.erb
<% options = {
  office: current_office
}%>

modal_div = document.getElementById('app-modal')

modal_div.innerHTML = "<%= j render 'destroy_modal', options %>"

var app_modal = new bootstrap.Modal(document.getElementById('app-modal'))

app_modal.show()

app/views/offices/edit.html.erb
<% breadcrumb :edit_office, current_office %>

<div class="col-12 mb-2">
  <div class="card">
    <div class="card-body">
      <%= render 'form', office: @office, url: office_url(@office.slug) %>
    </div>
  </div>
</div>

<h5> Members </h5>
<%= render 'members/index', members: @office.members %>

<div class="row">
  <div class="col-lg-12 mb-2">
    <h5> Settings </h5>
    <div class="card">
      <div class="card-body">
        <h5>Delete Office</h5>
        <p>Delete this office and all of its entries. This action is irreversible. </p>
        <%= link_to [:destroy_modal, current_office], class: 'btn btn-danger', remote: true do %>
          <i class="fa fa-trash me-1"></i> Delete Office
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/offices/index.html.erb
<div class='d-flex align-items-center'>
  <h3>Offices</h3>
  <div class='page-control ms-auto my-3'>
    <%= link_to [:new, :office], class: 'btn btn-info btn-sm' do %>
      <i class="fa fa-circle-plus me-1"></i> New Office
    <% end %>
  </div>
</div>
<% if @memberships.count.positive? %>
  <% search_params = {}  %>
  <%= form_tag offices_path(search_params), method: :get do %>
    <div class="row">
      <hr/>
      <div class="col-md-3 offset-md-7 pe-md-0">
        <div class='input-group mb-2'>
          <%= search_field_tag :search, params[:search], class: 'form-control', placeholder: 'Search by office name', aria: { label: 'Search instance' } %>
        </div>
      </div>
      <div class="col-md-2 mb-2">
        <div class="dropdown">
          <div class="btn btn border bg-white form-control dropdown-toggle caret-end" href="#" role="button" id="sortOfficeDropdown" data-bs-toggle="dropdown" aria-expanded="false">
            <span class='float-start'>
              <%= find_sort_item_by_code(params[:sort])[:name] %>
            </span>
          </div>

          <ul class="dropdown-menu form-control" aria-labelledby="sortOfficeDropdown">
            <% office_sort_options.each do |item| %>
              <% active_option = item[:code] == params[:sort] ? 'active' : '' %>
              <% case item[:type] %>
              <% when :label %>
                <label class='ps-3 fw-bold'>
                  <%= item[:name] %>
                </label>
              <% when :option%>
                <li>
                  <%= link_to item[:name], offices_path(search_params.merge(sort: item[:code])), class: "dropdown-item ps-5 #{active_option}" %>
                </li>
              <% end %>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
  <% end %>

  <div id="offices">
  <% @memberships.each do |membership| %>
    <% office = membership.office %>
    <div class="card mb-2 col-12">
      <div class="card-body">
        <div class='d-flex'>
          <div class='rounded squared-50 me-3' style='background-color: <%= office.thumbnail_color %>; '>
            <div class='thumbnail-text'>
              <%= office.name.split(' ').first(2).map { |name| name.first }.join.upcase %>
            </div>
          </div>
          <div>
            <span class="card-title h5">
              <%= link_to office.name, office_path(office.slug), class: 'text-primary no-decoration stretched-link' %>
            </span>
            <span class='badge bg-white border text-dark rounded-pill'>
              <%= membership.member_role %>
            </span>
            <div>
              <small class='text-secondary'><%= office.description %></small>
            </div>
            <div class=''>
              <div class=' text-muted'>
                <span class='me-2'>
                  <span> <i class="fa fa-shapes me-2"></i><b><%= office.data_models.count %></b></span> Templates
                </span>
                <span class='me-2'>
                  <span> <i class="fa fa-users me-2"></i><b><%= office.users.count %></b></span> Users
                </span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
  </div>
<% else %>
  <%= render 'empty' %>
<% end %>

  <style type="text/css" media="all">
.caret-end:before, .caret-end:after {
  float: right;
  margin-top: 10px;
}
</style>

app/views/offices/new.html.erb
<div class="row mt-2">
  <div class="col-md-3">
    <h4>Create new office</h4>
  </div>
  <div class="col-md-9 border-start">
    <div class='row'>
      <div class="col-12">
        <%= render 'breadcrumbs' %>
      </div>
    </div>
    <div class="card mt-2">
      <div class="card-body" data-controller='slug'>
        <%= render 'form', office: @office, url: offices_path %>
      </div>
    </div>
  </div>
</div>

app/views/offices/show.html.erb
  <div class='col-12 p-1'>
    <%= link_to 'New Entry', '', class: 'btn btn-primary float-end' %>
  </div>
  <% @instances.each do |instance| %>
    <div class="col-12 p-1">
      <div class="card pt-2 ps-3 pb-2 pe-3">
        <div class='d-flex justify-content-between'>
          <span class=text-dark style='font-size: .8rem;'>
            <b>
              <%= link_to  [current_office, instance], class: 'stretched-link text-success no-decoration' do %>
                <%= instance.data_model.name %> #<%=instance.id %>
              <% end %>
            </b>
            <span>
              @<%= instance.created_by.username %>
            </span>
            <span>·</span>
            <span class='text-dark'>
              <small><%= shorten_relative_time(instance.created_at) %></small>
            </span>
          </span>
          <span class='text-success'>
            <% count = instance.documents.order('documents.position DESC').count %>
            <span class='badge bg-info rounded-pill'>
              <%= pluralize(count, 'document') %>
            </span>
          </span>
        </div>
        <div class='row'>
          <% instance.properties.each do |prop| %>
            <div class='col-6 col-md-12 text-truncate'>
              <span>
                <b class='text-dark'><%= prop.name %>:</b>
              </span>
              <span class=''>
                <%= prop.value %>
              </span>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>