config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'pages#dashboard'
  get 'dashboard', to: 'pages#dashboard'

  # routes will start with /offices/<office.slug>/
  resources :offices, param: :slug do
    shallow_actions = %i[edit update show]

    member do
      get :destroy_modal
    end

    resources :members, only: %i[index new create] do
      member do
        patch :change_role
      end
    end

    resources :search_users, only: [:index], defaults: { format: :json }

    resources :templates, only: shallow_actions.push(:destroy) do
      member do
        get :destroy_modal
      end
    end

    resources :model_properties, only: shallow_actions.push(:destroy) do
      member do
        get :destroy_modal
      end
    end

    resources :documents, only: [:destroy] do
      member do
        get :destroy_modal
      end
    end

    resources :instances, only: shallow_actions.push(:destroy) do
      resources :documents

      member do
        get :destroy_modal
      end
    end

    resources :instance_properties, only: shallow_actions
    resources :data_models do
      member do
        get :destroy_modal
      end
      resources :model_properties, except: shallow_actions
      resources :instances, except: shallow_actions
      resources :templates, except: shallow_actions
    end
  end
end

app/models/data_model.rb
class DataModel < ApplicationRecord
  belongs_to :created_by, class_name: 'User'
  belongs_to :office

  has_many :properties, class_name: 'ModelProperty', dependent: :destroy
  has_many :instances, dependent: :destroy
  has_many :documents, through: :instances
  has_many :templates, dependent: :destroy
  has_many :instance_properties, through: :instances, source: :properties

  accepts_nested_attributes_for :properties

  validate :no_duplicate_codes, on: :create
  validates :name, presence: true

  def no_duplicate_codes
    if properties.group_by(&:code).values.detect { |arr| arr.size > 1 }
      errors.add(:base, 'Field Code should be unique')
    end
  end
end

app/controllers/data_models_controller.rb
class DataModelsController < ApplicationController
  before_action :authorize_admin!

  layout 'office'

  def index
    @data_models = current_office.data_models.page(params[:page])
    if @data_models.count.zero?
      return redirect_to [:new, current_office, :data_model], notice: 'Create your first Data Model here'
    end

    if params[:search].present?
      @data_models = @data_models.where('lower(name) LIKE ?', "%#{params[:search].downcase}%")
    end
    @params = request.query_parameters
  end

  def new
    @data_model = current_user.created_data_models.new
    @data_model.properties.build
  end

  def create
    @data_model = current_user.created_data_models.new data_model_params
    @data_model.office = current_office
    if data_model.save
      redirect_to [current_office, @data_model]
    else
      render :new
    end
  end

  def edit
    data_model
  end

  def update
    if data_model.update(data_model_params)
      redirect_to [current_office, data_model]
    else
      render :edit
    end
  end

  def show
    data_model
    @model_properties = data_model.properties.order('model_properties.position ASC')
    @templates = data_model.templates.order('templates.name ASC')
  end

  def destroy_modal
    data_model
  end

  def destroy
    data_model.destroy
    redirect_to [current_office, :data_models], notice: 'Template deleted'
  end

  private

  def data_model
    @data_model ||= DataModel.find(params[:id])
  end

  def data_model_params
    params.require(:data_model).permit(:name, :thumbnail_color, properties_attributes: [:name, :code, :required])
  end
end

app/views/data_models/_data_model.html.erb
<% office = data_model.office %>
<td>
  <div class='row'>
    <div class='col-4'>
      <%= link_to data_model.name, office_data_model_path(data_model.id, office_slug: office.slug) %>
    </div>
    <div class='col-4'>
      <%= data_model.properties.pluck(:name).join(', ') %>
    </div>
    <div class='col-4'>
      <%= link_to 'Edit', edit_office_data_model_path(data_model, office_slug: office.slug) %>
    </div>
  </div>
</div>
<hr/>

app/views/data_models/_destroy_modal.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-header">
      <h5 class="modal-title">Delete <%= data_model.name %> template</h5>
    </div>
    <div class="modal-body">
        This <b>template</b> contains:

        <ul>
          <li>
            <span class='text-warning'>
              <%= pluralize(data_model.instances.count, 'entry') %>
            </span>
          </li>
          <li>
            <span class='text-warning'>
              <%= pluralize(data_model.documents.count, 'document') %>
            </span>
          </li>
        </ul>
      </p>
    </div>
    <div class="modal-footer">
      <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
      <%= link_to 'Delete', [office, data_model], method: :delete, class: 'btn btn-danger' %>
    </div>
  </div>
</div>

app/views/data_models/_form.html.erb
<%= render 'errors', object: data_model  %>
<%= form_for data_model, url: url do |f| %>
  <div class='card mb-2'>
    <div class='card-body'>
      <div class='row'>
        <h5>Template Info</h5>
        <div class="form-group mb-3">
          <%= f.label :name, class: 'form-label' %>
          <%= f.text_field :name, class: 'form-control' %>
        </div>

        <div class='form-group mb-3'>
          <%= f.label :description, class: 'form-label' %>
          <%= f.text_area :description, class: 'form-control', rows: 5 %>
        </div>

        <div class="form-group mb-3 visually-hidden" data-controller='random-color'>
          <%= f.label :thumbnail_color, 'Thumbnail Color (#hex-value)', class: 'form-field' %>
          <%= f.text_field :thumbnail_color, class: 'form-control', 'data-random-color-target': 'thumbnailColor' %>
        </div>
      </div>
    </div>
  </div>

  <div class='card mb-2' data-controller='data-model-fields'>
      <div class="card-header bg-white no-border-bottom" style='border: none;'>
        <h5 class='card-title mb-0'>Fields</h5>
      </div>
    <%= f.fields_for :properties do |property_builder| %>
      <div data-data-model-fields-target='fields'>
        <%= render 'model_properties/fields_for_nested_attrs', f: property_builder%>
      </div>
    <% end %>
    <div class="card-footer bg-white">
      <div class="">
        <%= link_to_add_fields f, :properties, 'model_properties/fields_for_nested_attrs',
          class: 'no-decoration', 'data-action' => 'click->data-model-fields#addField',
          'data-data-model-fields-target' => 'addFieldLink' do %>
          <i class='fa fa-plus ms-2'></i>
          <span class='ms-4'>
            Add another field
          </span>
        <% end %>
      </div>
    </div>
  </div>
  <hr/>
  <div class='form-group float-end'>
    <%= f.submit class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/data_models/_templates.html.erb
<div class="card">
  <div class="card-body">
    <div class="row mb-2">
      <div class="col-sm-8">
        <%= link_to [:new, office, data_model, :template], class: 'btn btn-info btn-sm' do %>
          <i class="fa fa-circle-plus me-1"></i> New Template
        <% end %>
      </div>
    </div>
    <table class='table table-striped table-borderless table-hover'>
      <tbody>
        <% templates.each do |template| %>
          <tr>
            <td>
              <div class="row">
                <span class='ml-3 text-wrap'>
                  <b>
                    <%= link_to template.name, office_template_path(template.id, office_slug: office.slug), class: 'text-primary' %>
                  </b>
                  <br/>
                  <div>
                    <%= template.description %>
                  </div>
                </span>
            </td>

            <td class='pe-1 text-end'>
              <%= link_to [:edit, office, template], class: 'no-decoration me-1' do %>
                <i class="fa fa-pen-to-square text-warning"></i>
              <% end %>
              <%= link_to [:destroy_modal, office, template], remote: true, class: 'no-decoration me-1' do %>
                <i class="fa fa-trash text-danger"></i>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/data_models/destroy_modal.js.erb
<% options = {
  data_model: @data_model,
  office: current_office
}%>

modal_div = document.getElementById('app-modal')

modal_div.innerHTML = "<%= j render 'destroy_modal', options %>"

var app_modal = new bootstrap.Modal(document.getElementById('app-modal'))

app_modal.show()

app/views/data_models/edit.html.erb
<% breadcrumb :edit_data_model, @data_model, current_office %>
<div class="col-12">
  <%= render 'errors', object: @data_model  %>
  <%= form_for @data_model, url: office_data_model_path(current_office.slug) do |f| %>
    <div class='card mb-2'>
      <div class='card-body'>
        <div class='row'>
          <h5>Template Info</h5>
          <div class="form-group mb-3">
            <%= f.label :name, class: 'form-label' %>
            <%= f.text_field :name, class: 'form-control' %>
          </div>

          <div class='form-group mb-3'>
            <%= f.label :description, class: 'form-label' %>
            <%= f.text_area :description, class: 'form-control', rows: 5 %>
          </div>
        </div>
      </div>
    </div>

    <div class='form-group float-end'>
      <%= f.submit class: 'btn btn-primary' %>
    </div>
  <% end %>
</div>

app/views/data_models/index.html.erb
<% breadcrumb :data_models, current_office %>
<div class='d-flex align-items-center'>
  <h3>Templates</h3>
  <div class='page-control ms-auto my-3'>
    <%= link_to [:new, current_office, :data_model], class: 'btn btn-info btn-sm' do %>
      <i class="fa fa-circle-plus me-1"></i> New Template
    <% end %>
  </div>
</div>
<hr/>

<%# <div class="col-md-3 offset-md-9 pe-md-0"> %>
<div class="col-md-3 offset-md-9">
  <% search_params = @params.merge({ slug: current_office.slug }) %>

  <%= form_tag office_data_models_path(search_params), method: :get do %>
    <div class='input-group mb-2'>
      <%= search_field_tag :search, params[:search], class: 'form-control', placeholder: 'Search', aria: { label: 'Search Templates' } %>
    </div>
  <% end %>
</div>

<div class="data_models">
  <% @data_models.each do |data_model| %>
    <div class="card mb-2 col-12">
      <div class="card-body">
        <div class='d-flex'>
          <div class='rounded squared-50 me-3' style='background-color: <%= data_model.thumbnail_color %>; '>
            <div class='thumbnail-text'>
              <%= data_model.name.split(' ').first(2).map { |name| name.first }.join.upcase %>
            </div>
          </div>
          <div>
            <span class="card-title h5">
              <%= link_to data_model.name, [current_office, data_model], class: 'text-primary no-decoration stretched-link' %>
            </span>
            <div class=''>
              <div class=' text-muted'>
                <span class='me-2'>
                  <span><i class='fa fa-line me-2'></i><%= data_model.properties.count %></span> Fields
                </span>
              <span>
              </span>
                <span class='me-2'>
                  <span><i class='fa fa-file me-2'></i> <%= data_model.templates.count %></span>
                </span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
  <%= paginate @data_models %>
</div>

app/views/data_models/new.html.erb
<% breadcrumb :new_data_model, current_office %>
<div class="col-12">
  <%= render "form", data_model: @data_model, url: office_data_models_path(current_office.slug) %>
</div>

app/views/data_models/show.html.erb
<% breadcrumb :data_model, @data_model, current_office %>
<%= render 'flash' %>

<div class="col-md-12">
  <div class='card mb-3'>
    <div class='card-body'>
      <div class=''>
        <h4 class='text-dark'>
          <%= @data_model.name %>
          <%= link_to edit_office_data_model_path(@data_model.id, office_slug: current_office.slug), class: 'text-dark ms-2' do %>
            <i class="fa fa-pen-to-square"></i>
          <% end %>
        </h4>
        <p class='text-dark'>Created at: <%= @data_model.created_at.strftime('%b %d, %Y') %>
      </div>
      <div class='mt-3'>
        <h6>Description</h6>
        <p>
          <%= @data_model.description %>
        <p>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-lg-8 mb-2">
      <h5> Properties </h5>
      <%= render 'model_properties/index', data_model: @data_model, model_properties: @data_model.properties %>
    </div>
    <div class="col-lg-4">
      <h5 class=''>
        Templates
      </h5>
      <%= render "templates", templates: @templates, office: current_office, data_model: @data_model %>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-8 mb-2">
      <h5> Settings </h5>
      <div class="card">
        <div class="card-body">
          <h5>Delete Template</h5>
          <p>Delete this template and all of its data. This action is irreversible. </p>
          <%= link_to [:destroy_modal, current_office, @data_model], class: 'btn btn-danger', remote: true do %>
            <i class="fa fa-trash me-1"></i> Delete Template
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>