config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'pages#dashboard'
  get 'dashboard', to: 'pages#dashboard'

  # routes will start with /offices/<office.slug>/
  resources :offices, param: :slug do
    shallow_actions = %i[edit update show]

    member do
      get :destroy_modal
    end

    resources :members, only: %i[index new create] do
      member do
        patch :change_role
      end
    end

    resources :search_users, only: [:index], defaults: { format: :json }

    resources :templates, only: shallow_actions.push(:destroy) do
      member do
        get :destroy_modal
      end
    end

    resources :model_properties, only: shallow_actions.push(:destroy) do
      member do
        get :destroy_modal
      end
    end

    resources :documents, only: [:destroy] do
      member do
        get :destroy_modal
      end
    end

    resources :instances, only: shallow_actions.push(:destroy) do
      resources :documents

      member do
        get :destroy_modal
      end
    end

    resources :instance_properties, only: shallow_actions
    resources :data_models do
      member do
        get :destroy_modal
      end
      resources :model_properties, except: shallow_actions
      resources :instances, except: shallow_actions
      resources :templates, except: shallow_actions
    end
  end
end

app/models/model_property.rb
class ModelProperty < ApplicationRecord
  belongs_to :data_model
  has_many :instance_properties, dependent: :nullify

  validates :name, presence: true
  validates :code, uniqueness: { scope: :data_model_id }, presence: true,
                   format: {
                     with: /\A[a-zA-Z0-9_]+\z/,
                     message: 'only allows a-z, A-Z and 0-9 and underscore'
                   }

  def data_for_instance_property
    attributes.slice('name', 'code', 'required', 'position', 'default_value')
              .merge(
                'value': default_value,
                'model_property': self
              )
  end
end

app/controllers/model_properties_controller.rb
class ModelPropertiesController < ApplicationController
  before_action :authorize_admin!

  layout 'office'

  def new
    @model_property = data_model.properties.new
    respond_to do |format|
      format.html
      format.js
    end
  end

  def create
    @model_property = data_model.properties.new property_params
    respond_to do |format|
      format.html do
        if model_property.save
          redirect_to [current_office, data_model], notice: 'Property created'
        else
          render :new, status: :unprocessable_entity
        end
      end
      format.js { model_property.save }
    end
  end

  def edit
    model_property
  end

  def update
    if model_property.update(property_params)
      data_model = model_property.data_model

      redirect_to [current_office, data_model], notice: 'Property updated'
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy_modal
    model_property
  end

  def destroy
    data_model = model_property.data_model
    model_property.destroy
    redirect_to [current_office, data_model], notice: 'Field deleted'
  end

  private

  def data_model
    @data_model ||= DataModel.find(params[:data_model_id])
  end

  def model_property
    @model_property ||= current_office.model_properties.find(params[:id])
  end

  def property_params
    params.require(:model_property).permit(:name, :required, :code, :header_visibility, :description, :position,
                                           :default_value)
  end
end

app/views/model_properties/_destroy_modal.html.erb
<div class="modal-dialog">
  <div class="modal-content">
    <div class="modal-header">
      <h5 class="modal-title">Delete <%= model_property.name %> Field</h5>
    </div>
    <div class="modal-body">
        This <b>field</b> is used in:
        <ul>
          <li>
            <span class='text-warning'>
              <%= pluralize(model_property.instance_properties.count, 'entry') %>
            </span>
          </li>
        </ul>
      </p>
    </div>
    <div class="modal-footer">
      <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
      <%= link_to 'Delete', [office, model_property], method: :delete, class: 'btn btn-danger' %>
    </div>
  </div>
</div>

app/views/model_properties/_fields_for_nested_attrs.html.erb
<div class='card-body border-top' data-data-model-fields-target='fields'>
  <fieldset class='field-group' data-controller='slug'>
    <div class="field-group-icon p-2 text-dark">
      <i class='fa fa-grip-vertical'></i>
    </div>

    <%= f.label :name, 'Field Name', class: 'form-label field-label mb-1' %>
    <%= f.text_field :name, class: 'form-control field-grid-first mb-3',
      placeholder: 'First Name',
      required: true,
      'data-slug-target': 'name',
      'data-action': 'keyup->slug#updateSlug'
    %>
  <div class='form-group p-2 ms-3 field-trash'>
    <%= link_to '', class: 'text-danger' do%>
      <i class="fa fa-trash"></i>
    <% end %>
  </div>
  <div class='field-grid-next'>
    <div class="mb-3">
      <%= f.label :code, 'Field code', class: 'form-label mb-1' %>
      <%= f.text_field :code, class: 'form-control', placeholder: 'first_name', required: true,
        'data-slug-target': 'slug' %>
    </div>
    <div class="d-flex">
      <div class="form-check form-switch">
        <%= f.check_box :required, class: 'form-check-input text-success' %>
      </div>
      <%= f.label :required, class: 'form-check-label' %>
    </div>
  </div>
  </fieldset>
</div>

app/views/model_properties/_form.html.erb
<% if model_property.errors.count.positive? %>
  <div class='error'>
    <% model_property.errors.each do |error| %>
      <div class="alert alert-danger">
        <%= error.full_message %>
      </div>
    <% end %>
<% end %>
<%= form_for model_property, url: url do |f| %>
  <%= render "form_fields", f: f %>
<% end %>

app/views/model_properties/_form_fields.html.erb
<div class="row">
  <div class="col-md-6" data-controller='slug' data-slug-delimiter-value='_'>
    <div class='mb-3'>
      <%= f.label :name, 'Field Name', class: 'form-label' %>
      <%= f.text_field :name, class: 'form-control', placeholder: 'Enter property name.', required: true,
        'data-slug-target': 'name',
        'data-action': 'keyup->slug#updateSlug'
       %>
    </div>

    <div class='mb-3'>
      <%= f.label :code, 'Field code', class: 'form-label' %>
      <%= f.text_field :code, class: 'form-control', placeholder: 'Enter unique code for property', required: true,
          'data-slug-target': 'slug' %>
    </div>

    <div class='mb-3'>
      <%= f.label :description, class: 'form-label' %>
      <%= f.text_area :description, class: 'form-control', rows: 5 %>
    </div>
  </div>
  <div class="col-md-6">
    <div class='mb-3'>
      <%= f.label :default_value, class: 'form-label' %>
      <%= f.text_field :default_value, class: 'form-control', placeholder: 'Enter default value' %>
    </div>
    <div class='mb-3'>
      <%= f.label :position, class: 'form-label' %>
      <%= f.number_field :position, class: 'form-control', placeholder: 'Enter default value' %>
    </div>
    <div class="mb-3">
      <%= f.label :required, class: 'form-check-label' %>
      <div class="form-check form-switch float-end">
        <%= f.check_box :required, class: 'form-check-input text-success' %>
      </div>
    </div>
    <div class="mb-3">
      <%= f.label :header_visiblity, class: 'form-check-label' %>
      <div class="form-check form-switch float-end">
        <%= f.check_box :header_visibility, class: 'form-check-input text-success' %>
      </div>
    </div>
  </div>
  <div class="col-12">
    <%= f.submit class: 'btn btn-success mb-3 float-end' %>
  </div>
</div>

app/views/model_properties/_form_modal.html.erb
<div class="modal-dialog modal-lg">
  <div class="modal-content">
    <%= form_for model_property, url: url, remote: remote  do |f| %>
      <div class="modal-header">
        <h5 class='modal-title'> Create new <%= @data_model.name %>'s Property </h5>
      </div>
      <div class="modal-body">
        <% if model_property.errors.count.positive? %>
          <div class='error'>
            <% model_property.errors.each do |error| %>
              <div class="alert alert-danger">
                <%= error.full_message %>
              </div>
            <% end %>
        <% end %>
        <%= render "form_fields", f: f %>
      </div>
    <% end %>
  </div>
</div>

app/views/model_properties/_index.html.erb
<div class="card mt-2">
  <div class="card-body">
    <div class="row mb-2">
      <div class="col-sm-5">
        <%= link_to new_office_data_model_model_property_path(data_model.id, office_slug: current_office.slug), class: 'btn btn-info btn-sm' do %>
          <i class="fa fa-circle-plus me-1"></i> New Property
        <% end %>
      </div>
    </div>
    <table class='table table-striped table-borderless table-hover'>
      <thead>
        <tr>
          <th>Field</th>
          <th>Code</th>
          <th>Header</th>
          <th>Position</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        <%= render model_properties %>
      </tbody>
    </table>
  </div>
</div>

app/views/model_properties/_model_property.html.erb
<tr>
  <td>
    <div>
      <div>
        <%= model_property.name %>
      </div>
      <div>
        <% if model_property.required? %>
          <small class='text-danger'>
            Required
          </small>
        <% else  %>
          <small class='text-success'>
            Optional
          </small>
        <% end %>
      </div>
    </div>
  </td>
  <td>
    <%= model_property.code %>
  </td>
  <td>
    <% if model_property.header_visibility? %>
      <i class="fa fa-check text-success"></i>
    <% end %>
  </td>
  <td>
    <%= model_property.position %>
  </td>
  <td class='pe-2'>
    <%= link_to edit_office_model_property_path(model_property.id, office_slug: current_office.slug), class: 'text-warning no-decoration me-1' do %>
      <i class="fa fa-pen-to-square"></i>
    <% end %>
    <%= link_to [:destroy_modal, current_office, model_property], remote: true, class: 'no-decoration' do %>
      <i class="fa fa-trash text-danger "></i>
    <% end %>
  </td>
</tr>

app/views/model_properties/create.js.erb
<% if @model_property.persisted? %>
    location.reload();
<% else %>
  <% options = {
    url: [current_office, @model_property.data_model, :model_properties],
    model_property: @model_property,
    remote: true
  } %>

  modal_div = document.getElementById('app-modal')

  modal_div.innerHTML = "<%= j render 'form_modal', options%>"
  var app_modal = new bootstrap.Modal(document.getElementById('app-modal'))
<% end %>

app/views/model_properties/destroy_modal.js.erb
<% options = {
  model_property: @model_property,
  office: current_office
}%>

modal_div = document.getElementById('app-modal')

modal_div.innerHTML = "<%= j render 'destroy_modal', options %>"

var app_modal = new bootstrap.Modal(document.getElementById('app-modal'))

app_modal.show()

app/views/model_properties/edit.html.erb
<% breadcrumb :edit_model_property, @model_property, current_office %>
<h5> Edit model property </h5>

<div class='card'>
  <div class='card-body'>
  <%= render "form", model_property: @model_property, url: office_model_property_path(@model_property.id, office_slug: current_office.slug), remote: false %>
  </div>
</div>

app/views/model_properties/new.html.erb
<% breadcrumb :new_model_property, @model_property, current_office %>
<h3> Create <%= @data_model.name %>'s Property </h3>

<div class='card'>
  <div class='card-body'>
    <%= render "form", model_property: @model_property, url: [current_office, @data_model, :model_properties], remote: false%>
  </div>
</div>

app/views/model_properties/new.js.erb
<% options = {
  url: [current_office, @data_model, :model_properties],
  model_property: @model_property,
  remote: true
} %>

modal_div = document.getElementById('app-modal')

modal_div.innerHTML = "<%= j render 'form_modal', options%>"
var app_modal = new bootstrap.Modal(document.getElementById('app-modal'))

app_modal.show()